### ISSUE TITLE
Add Statistics & Metric information to project

### ISSUE THREAD

**Issue by trystant** [ZaBAOW/Notice_M3#2]
The intent regarding Twitch stats and how they are collected should not be left to the imagination of the user, but explained either within the app or documentation associated with it.

**Comment by ZaBAOW** [comment]
I have added information to ReadMe.md that explains that the data being parse is being calculated as messages/minute.  And that the initial results when a stream is opened is treated as the threshold for the channel's chat.  I have also explained that if the threshold is either met or passed in the following tests, a notification will be sent to the user.
