### ISSUE TITLE
Buttons causing error involving Content Security Policy

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/Notice_M3#3]
when any button on extension is clicked the following error appears in the console.

index.html:17 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' https://apis.google.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

have seen this error in the past, will probably have to update manifest.json.

**Comment by trystant** [comment]
I believe that you have resolved this in your "buttons" branch. How did you solve this error?

**Comment by ZaBAOW** [comment]
I created a separate js file for popup scripts, as keeping them in the content scripts was causing the CSP violation.  This new js file was then set up to communicate to the content scripts via messages in order to make the popup window buttons functional.
