### ISSUE TITLE
Displaying variables form app.js on index.html body.

### ISSUE THREAD

**Issue by ZaBAOW** [ZaBAOW/Notice_M3#4]
I want a variable called threshold to be displayed in real time on Notice_M3's popup window.   I have tried using document.write() to no success, however every time i go back and research the issue, the same or very similar solutions including document.write() appear.

**Comment by trystant** [comment]
What solutions have you tried so far? Can you post the links in this issue?

**Comment by ZaBAOW** [comment]
I have been able to get the threshold to show up on the popup window using the document.write() method.  However, this causes a document.write() to occur on the main webpage as well where only the element created by the document write to be the only thing to show up.

**Comment by ZaBAOW** [comment]
I was able to get targeted variables to show up on the popup window by utilizing the sendMessage/onMessage() methods from the chrome api.  When opened, the popup window would send a blank message to the background and when that message was received, the background would send a message back to the popup window with the threshold value.  That value would then be written only onto the popup window by first targeting a pre-existing element in the html by its id and then adding the .innerHTML method and designating the value to the threshold value that was received.
